"""
gui.py — Graphical interface for the Paulus Seating Randomizer.

Written by Claude Sonnet 4.6 (Anthropic) for the Paulus project.
"""

import csv
import sys
from pathlib import Path

try:
    import customtkinter as ctk
except ImportError:
    print(
        "customtkinter is required.\n"
        "Install it with:  pip install customtkinter"
    )
    sys.exit(1)

from tkinter import filedialog, messagebox

from SeatingRandomizer import SeatingRandomizer

# ── Constants ──────────────────────────────────────────────────────────────────

RULES = {"different_gender_pairing": True, "no_repeat": True}

DARK_BG   = "#0f172a"
CARD_BG   = "#1e293b"
ACCENT    = "#38bdf8"
ACCENT2   = "#818cf8"
GREEN     = "#22c55e"
GREEN_HOV = "#16a34a"
BLUE      = "#3b82f6"
BLUE_HOV  = "#2563eb"
TEXT      = "#e2e8f0"
SUBTEXT   = "#64748b"
SEP       = "#334155"

FONT_FAMILY = "Segoe UI"

# ── App ────────────────────────────────────────────────────────────────────────

class PaulusApp(ctk.CTk):
    def __init__(self):
        super().__init__()

        ctk.set_appearance_mode("dark")
        ctk.set_default_color_theme("blue")

        self.title("Paulus Shuffle")
        self.geometry("1200x760")
        self.minsize(960, 640)
        self.configure(fg_color=DARK_BG)

        # App icon (generated by create_icon.py)
        _icon = Path(__file__).with_name("icon.png")
        if _icon.exists():
            try:
                from PIL import ImageTk, Image as _Img
                _img = _Img.open(_icon).resize((64, 64), _Img.LANCZOS)
                self._icon_img = ImageTk.PhotoImage(_img)
                self.iconphoto(True, self._icon_img)
            except Exception:
                pass  # icon is optional

        # State
        self._students_file: Path | None = None
        self._pairs_file:    Path | None = None
        self._current_pairs: list        = []

        self._build_header()
        self._build_main()
        self._build_footer()

    # ── Header ─────────────────────────────────────────────────────────────────

    def _build_header(self):
        header = ctk.CTkFrame(self, height=72, corner_radius=0, fg_color=CARD_BG)
        header.pack(fill="x", side="top")
        header.pack_propagate(False)

        inner = ctk.CTkFrame(header, fg_color="transparent")
        inner.pack(fill="both", expand=True, padx=28)

        # App name
        ctk.CTkLabel(
            inner,
            text="Paulus",
            font=ctk.CTkFont(family=FONT_FAMILY, size=30, weight="bold"),
            text_color=ACCENT,
        ).pack(side="left", pady=16)

        ctk.CTkLabel(
            inner,
            text="  Shuffle",
            font=ctk.CTkFont(family=FONT_FAMILY, size=22, weight="bold"),
            text_color=TEXT,
        ).pack(side="left", pady=16)

        # Tagline (right)
        ctk.CTkLabel(
            inner,
            text="Smart classroom seating made easy",
            font=ctk.CTkFont(family=FONT_FAMILY, size=12),
            text_color=SUBTEXT,
        ).pack(side="right", pady=16)

    # ── Main three-panel layout ────────────────────────────────────────────────

    def _build_main(self):
        main = ctk.CTkFrame(self, fg_color="transparent")
        main.pack(fill="both", expand=True, padx=20, pady=16)

        main.columnconfigure(0, weight=1)
        main.columnconfigure(1, weight=1)
        main.columnconfigure(2, weight=1)
        main.rowconfigure(0, weight=1)

        # ── Panel 1: Students ──────────────────────────────────────────────────
        p1 = self._make_panel(main, "Students", 0)

        self._students_box = self._make_textbox(p1)

        self._students_lbl = ctk.CTkLabel(
            p1,
            text="No students loaded",
            font=ctk.CTkFont(family=FONT_FAMILY, size=11),
            text_color=SUBTEXT,
        )
        self._students_lbl.pack(pady=(2, 6))

        ctk.CTkButton(
            p1,
            text="Import Students",
            command=self._load_students,
            height=38,
            corner_radius=8,
            font=ctk.CTkFont(family=FONT_FAMILY, size=13, weight="bold"),
            fg_color=BLUE,
            hover_color=BLUE_HOV,
        ).pack(fill="x", padx=14, pady=(0, 14))

        # ── Panel 2: Last Pairings ─────────────────────────────────────────────
        p2 = self._make_panel(main, "Last Pairings", 1)

        self._pairs_box = self._make_textbox(p2)

        self._pairs_lbl = ctk.CTkLabel(
            p2,
            text="No pairings loaded",
            font=ctk.CTkFont(family=FONT_FAMILY, size=11),
            text_color=SUBTEXT,
        )
        self._pairs_lbl.pack(pady=(2, 6))

        ctk.CTkButton(
            p2,
            text="Import Last Pairings",
            command=self._load_pairs,
            height=38,
            corner_radius=8,
            font=ctk.CTkFont(family=FONT_FAMILY, size=13, weight="bold"),
            fg_color=BLUE,
            hover_color=BLUE_HOV,
        ).pack(fill="x", padx=14, pady=(0, 14))

        # ── Panel 3: New Pairings / Randomise ─────────────────────────────────
        p3 = self._make_panel(main, "New Pairings", 2)

        self._results_box = self._make_textbox(p3)

        self._time_lbl = ctk.CTkLabel(
            p3,
            text="",
            font=ctk.CTkFont(family=FONT_FAMILY, size=11),
            text_color=SUBTEXT,
        )
        self._time_lbl.pack(pady=(2, 6))

        ctk.CTkButton(
            p3,
            text="Randomise",
            command=self._randomise,
            height=38,
            corner_radius=8,
            font=ctk.CTkFont(family=FONT_FAMILY, size=14, weight="bold"),
            fg_color=ACCENT2,
            hover_color="#6366f1",
        ).pack(fill="x", padx=14, pady=(0, 6))

        self._download_btn = ctk.CTkButton(
            p3,
            text="Download Pairings",
            command=self._download_pairs,
            height=38,
            corner_radius=8,
            font=ctk.CTkFont(family=FONT_FAMILY, size=13, weight="bold"),
            fg_color=GREEN,
            hover_color=GREEN_HOV,
            state="disabled",
        )
        self._download_btn.pack(fill="x", padx=14, pady=(0, 14))

    def _make_panel(self, parent, title: str, col: int) -> ctk.CTkFrame:
        """Create a card-style panel with a title and separator."""
        card = ctk.CTkFrame(parent, corner_radius=14, fg_color=CARD_BG)
        card.grid(row=0, column=col, sticky="nsew", padx=8)
        card.rowconfigure(1, weight=1)
        card.columnconfigure(0, weight=1)

        ctk.CTkLabel(
            card,
            text=title,
            font=ctk.CTkFont(family=FONT_FAMILY, size=16, weight="bold"),
            text_color=TEXT,
        ).pack(anchor="w", padx=18, pady=(18, 6))

        ctk.CTkFrame(card, height=1, fg_color=SEP, corner_radius=0).pack(
            fill="x", padx=14, pady=(0, 10)
        )

        return card

    def _make_textbox(self, parent) -> ctk.CTkTextbox:
        """Create a styled, read-only textbox for displaying list data."""
        box = ctk.CTkTextbox(
            parent,
            state="disabled",
            corner_radius=8,
            font=ctk.CTkFont(family="Consolas", size=13),
            fg_color="#0f172a",
            text_color=TEXT,
            scrollbar_button_color=SEP,
            activate_scrollbars=True,
            wrap="none",
        )
        box.pack(fill="both", expand=True, padx=14, pady=(0, 4))
        return box

    # ── Footer / status bar ────────────────────────────────────────────────────

    def _build_footer(self):
        footer = ctk.CTkFrame(self, height=34, corner_radius=0, fg_color=CARD_BG)
        footer.pack(fill="x", side="bottom")
        footer.pack_propagate(False)

        self._status_var = ctk.StringVar(value="Ready — import students to get started.")

        ctk.CTkLabel(
            footer,
            textvariable=self._status_var,
            font=ctk.CTkFont(family=FONT_FAMILY, size=11),
            text_color=SUBTEXT,
        ).pack(side="left", padx=18)

        ctk.CTkLabel(
            footer,
            text="Paulus Shuffle v1.0",
            font=ctk.CTkFont(family=FONT_FAMILY, size=11),
            text_color=SEP,
        ).pack(side="right", padx=18)

    # ── Actions ────────────────────────────────────────────────────────────────

    def _load_students(self):
        path = filedialog.askopenfilename(
            title="Select students CSV",
            filetypes=[("CSV files", "*.csv"), ("All files", "*.*")],
        )
        if not path:
            return

        self._students_file = Path(path)
        try:
            rows = []
            with self._students_file.open(newline="", encoding="utf-8") as f:
                reader = csv.DictReader(f)
                for row in reader:
                    rows.append(row)

            lines = []
            for r in rows:
                gender_icon = "♀" if r["gender"].strip().upper() == "F" else "♂"
                lines.append(f"{gender_icon}  {r['name']}")

            self._fill(self._students_box, lines)
            n = len(rows)
            self._students_lbl.configure(text=f"{n} student{'s' if n != 1 else ''} loaded")
            self._set_status(f"Loaded {n} students from {self._students_file.name}")

        except Exception as exc:
            messagebox.showerror("Error loading students", str(exc))

    def _load_pairs(self):
        path = filedialog.askopenfilename(
            title="Select last pairings CSV",
            filetypes=[("CSV files", "*.csv"), ("All files", "*.*")],
        )
        if not path:
            return

        self._pairs_file = Path(path)
        try:
            rows = []
            with self._pairs_file.open(newline="", encoding="utf-8") as f:
                reader = csv.reader(f)
                for row in reader:
                    if len(row) == 2:
                        rows.append(row)

            lines = [f"{r[0]}  ↔  {r[1]}" for r in rows]
            self._fill(self._pairs_box, lines)
            n = len(rows)
            self._pairs_lbl.configure(text=f"{n} pair{'s' if n != 1 else ''} loaded")
            self._set_status(f"Loaded {n} pairs from {self._pairs_file.name}")

        except Exception as exc:
            messagebox.showerror("Error loading pairings", str(exc))

    def _randomise(self):
        if not self._students_file:
            messagebox.showwarning(
                "No students",
                "Please import a students CSV file before randomising.",
            )
            return

        pairs_file = self._pairs_file or Path("last_pairs.csv")

        try:
            randomizer = SeatingRandomizer(self._students_file, pairs_file, RULES)
            pairs, duration = randomizer.randomize_neighbours()
        except Exception as exc:
            messagebox.showerror("Randomisation failed", str(exc))
            return

        self._current_pairs = pairs

        lines = [f"{s1.name}  ↔  {s2.name}" for s1, s2 in pairs]
        self._fill(self._results_box, lines)

        n = len(pairs)
        self._time_lbl.configure(
            text=f"{n} pair{'s' if n != 1 else ''}  •  generated in {duration:.4f}s"
        )
        self._download_btn.configure(state="normal")
        self._set_status(
            f"Randomised {n} pairs in {duration:.4f} seconds  —  "
            "click Download Pairings to save"
        )

    def _download_pairs(self):
        if not self._current_pairs:
            return

        path = filedialog.asksaveasfilename(
            title="Save pairings as CSV",
            defaultextension=".csv",
            initialfile="last_pairs.csv",
            filetypes=[("CSV files", "*.csv"), ("All files", "*.*")],
        )
        if not path:
            return

        try:
            with open(path, "w", newline="", encoding="utf-8") as f:
                writer = csv.writer(f)
                for s1, s2 in self._current_pairs:
                    writer.writerow([s1.name, s2.name])
            self._set_status(f"Pairings saved to {Path(path).name}")
        except Exception as exc:
            messagebox.showerror("Save failed", str(exc))

    # ── Helpers ────────────────────────────────────────────────────────────────

    def _fill(self, box: ctk.CTkTextbox, lines: list[str]):
        """Replace the contents of a read-only textbox."""
        box.configure(state="normal")
        box.delete("1.0", "end")
        box.insert("1.0", "\n".join(lines))
        box.configure(state="disabled")

    def _set_status(self, msg: str):
        self._status_var.set(msg)


# ── Entry point ────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    app = PaulusApp()
    app.mainloop()

# Credits
# This GUI was written by Claude Sonnet 4.6, Anthropic's AI model.
# Written with Claude Code — Anthropic's official CLI for Claude.
# Note: Claude only wrote this file; all other code was written by the project author.
